# Generated by Django 3.1 on 2020-08-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200816_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcatagory',
            new_name='subcategory',
        ),
    ]
