# Generated by Django 3.1 on 2020-08-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200817_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.IntegerField(default=' ', max_length=12)),
                ('desc', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
