# Generated by Django 3.1 on 2020-08-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200818_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
