# Generated by Django 3.1 on 2020-08-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200823_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='item_json',
            new_name='items_json',
        ),
        migrations.RenameField(
            model_name='orderupdate',
            old_name='order_Id',
            new_name='order_id',
        ),
    ]
